### PR TITLE
[RFC] 0004 Simple Build Extensibility

### PR DESCRIPTION
**Pull request by RandomByte**
Add a feature for basic customization of how a single UI5 project is being built.

Follow up of https://github.com/SAP/ui5-tooling/pull/4

### CODE REVIEW

**Comment by RandomByte** [comment]
In addition to the `beforeTask`/`afterTask` options, should there be an option to filter on the project type?

This would allow to insert tasks for e.g. application-projects only.

CC: @petermuessig, @matz3

**Comment by RandomByte** [comment]
Actually, never mind. It obviously only runs in the project it has been configured in, which has exactly one type 😅

**Comment by sebbi08** [comment]
Actually i like the idea that would give users the posibility to build one general extension for there projekts/libraries and reuse that

**Comment by RandomByte** [comment]
Test implementation: https://github.com/RandomByte/openui5-sample-app/pull/1

**Comment by RandomByte** [comment]
This RFC got implemented with https://github.com/SAP/ui5-builder/pull/106 and https://github.com/SAP/ui5-project/pull/64

This can be tested with UI5 CLI v0.2.4.  
Example setup: RandomByte/openui5-sample-app#1

Still missing: Updated documentation

**Comment by sebbi08** [comment]
> In addition to the `beforeTask`/`afterTask` options, should there be an option to filter on the project type?
> 
> This would allow to insert tasks for e.g. application-projects only.
> 
> CC: @petermuessig, @matz3

acctualy something like `first`/`last` would be nice so that certen tasks run at first / last always

**Comment by RandomByte** [comment]
Documentation got merged with https://github.com/SAP/ui5-project/pull/71. Available here: https://github.com/SAP/ui5-project/blob/master/docs/BuildExtensibility.md

**Comment by RandomByte** [comment]
@sebbi08 I created https://github.com/SAP/ui5-builder/issues/179 to keep track of your suggestion

**Comment by RandomByte** [comment]
@matz3 you think this is ready to be merged?

**Pull request merged**
