### PR TITLE
[INTERNAL] Add "ui5 remove" cli command documentation

### PR DESCRIPTION
**Pull request by tobiasso85**
Depends on https://github.com/SAP/ui5-cli/pull/327

### CODE REVIEW

**Comment by matz3** [comment]
Looks good. To be merged once ui5-cli v2.1.0 is released.

**Comment by KlattG** [comment]
How about version information?

**Comment by matz3** [comment]
> How about version information?

Do you mean to add a "since" information for the commands?
I think that would be very helpful. We should do this for "use", "add" (since v2.0) and "remove" (since v2.1).

**Comment by KlattG** [comment]
> > How about version information?
> 
> Do you mean to add a "since" information for the commands?
> I think that would be very helpful. We should do this for "use", "add" (since v2.0) and "remove" (since v2.1).

I mean that the CLI version is mentioned several times in the Configuration, so I'm a bit surprised that it's not mentioned here at all.

**Comment by tobiasso85** [comment]
> > > How about version information?
> > 
> > 
> > Do you mean to add a "since" information for the commands?
> > I think that would be very helpful. We should do this for "use", "add" (since v2.0) and "remove" (since v2.1).
> 
> I mean that the CLI version is mentioned several times in the Configuration, so I'm a bit surprised that it's not mentioned here at all.

will be addressed in separate change

**Pull request merged**
